// Bundle three.js and the few add-ons the app uses into one minified ES module, so the site has no CDN dependency
// (school networks sometimes block CDNs).  Usage: node tools/vendor.mjs
import { build } from 'esbuild';
import fs from 'node:fs';

const entry = `
export * from 'three';
export { OrbitControls } from 'three/addons/controls/OrbitControls.js';
export { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
export { MeshoptDecoder } from 'three/addons/libs/meshopt_decoder.module.js';
export { computeBoundsTree, disposeBoundsTree, acceleratedRaycast } from 'three-mesh-bvh';
`;
const out = 'public/vendor/three-bundle.js';
await build({
  stdin: { contents: entry, resolveDir: process.cwd(), sourcefile: 'vendor-entry.js' },
  bundle: true, format: 'esm', minify: true, target: 'es2020', outfile: out, legalComments: 'inline',
});
const three = JSON.parse(fs.readFileSync('node_modules/three/package.json')).version;
const bvh = JSON.parse(fs.readFileSync('node_modules/three-mesh-bvh/package.json')).version;
const src = fs.readFileSync(out, 'utf8');
fs.writeFileSync(out, `/* three.js r${three.split('.')[1]} (MIT) + three-mesh-bvh ${bvh} (MIT) — generated by tools/vendor.mjs */\n${src}`);
console.log(`wrote ${out} ${(fs.statSync(out).size / 1024).toFixed(0)} KB`);
